/*
module.exports = {
    HTTP_STATUS_OK: 200,
    HTTP_STATUS_CREATED: 201,
    HTTP_STATUS_ACCEPTED:202,
    HTTP_STATUS_NO_CONTENT: 204,
    HTTP_STATUS_REDIRECT: 302,
    HTTP_STATUS_BAD_REQUEST: 400,
    HTTP_STATUS_SERVICE_UNAUTHORIZED: 401,
    HTTP_STATUS_SERVICE_FORBIDDEN: 403,
    HTTP_STATUS_RESOURCE_NOT_FOUND: 404,
    HTTP_STATUS_CONFLICT: 409,
    HTTP_STATUS_INTERNAL_SERVER_ERROR: 500,
    HTTP_STATUS_NOT_IMPLEMENTED: 501,
    HTTP_STATUS_SERVICE_UNAVAILABLE: 505, 
    HTTP_CLIENT_CALLBACK: '/',
    HTTP_HEADER_ORIGIN: 'Origin',

    ROLE_SUPER_ADMIN: 'superAdmin',
    ROLE_ADMIN: 'admin',
    ROLE_STAFF: 'staff',
    ROLE_MEMBER: 'member',
 
    //Photo types
    PHOTO_TYPES_GALLERY:"Gallery",
    PHOTO_TYPES_FOOD:"Event",
    PHOTO_TYPES_OTHER:"Other",

    //Communication Types
    CONTACT_TYPE_EMAIL: "email",
    CONTACT_TYPE_PHONE: "phone",

    //Queue
    PHOTO_ARRIVAL_QUEUE: "PHOTO_ARRIVAL_QUEUE",
    SEND_SINGLE_TICKET_QUEUE:"SEND_SINGLE_TICKET_QUEUE",
    CREATE_TICKET_FROM_FILE_UPLOAD:"CREATE_TICKET_FROM_FILE_UPLOAD"
}
*/
export const HTTP_STATUS_OK = 200;
export const HTTP_STATUS_CREATED = 201;
export const HTTP_STATUS_ACCEPTED = 202;
export const HTTP_STATUS_NO_CONTENT = 204;
export const HTTP_STATUS_REDIRECT = 302;
export const HTTP_STATUS_BAD_REQUEST = 400;
export const HTTP_STATUS_SERVICE_UNAUTHORIZED = 401;
export const HTTP_STATUS_SERVICE_FORBIDDEN = 403;
export const HTTP_STATUS_RESOURCE_NOT_FOUND = 404;
export const HTTP_STATUS_CONFLICT = 409;
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
export const HTTP_STATUS_NOT_IMPLEMENTED = 501;
export const HTTP_STATUS_SERVICE_UNAVAILABLE = 505;

export const HTTP_CLIENT_CALLBACK = '/';
export const HTTP_HEADER_ORIGIN = 'Origin';

export const ROLE_SUPER_ADMIN = 'superAdmin';
export const ROLE_ADMIN = 'admin';
export const ROLE_STAFF = 'staff';
export const ROLE_MEMBER = 'member';

export const PHOTO_TYPES_GALLERY = "Gallery";
export const PHOTO_TYPES_FOOD = "Event";
export const PHOTO_TYPES_OTHER = "Other";

export const CONTACT_TYPE_EMAIL = "email";
export const CONTACT_TYPE_PHONE = "phone";

export const PHOTO_ARRIVAL_QUEUE = "PHOTO_ARRIVAL_QUEUE";
export const SEND_SINGLE_TICKET_QUEUE = "SEND_SINGLE_TICKET_QUEUE";
export const CREATE_TICKET_FROM_FILE_UPLOAD = "CREATE_TICKET_FROM_FILE_UPLOAD";

