module.exports = {
    HTTP_STATUS_OK: 200,
    HTTP_STATUS_CREATED: 201,
    HTTP_STATUS_ACCEPTED:202,
    HTTP_STATUS_NO_CONTENT: 204,
    HTTP_STATUS_REDIRECT: 302,
    HTTP_STATUS_BAD_REQUEST: 400,
    HTTP_STATUS_SERVICE_UNAUTHORIZED: 401,
    HTTP_STATUS_SERVICE_FORBIDDEN: 403,
    HTTP_STATUS_RESOURCE_NOT_FOUND: 404,
    HTTP_STATUS_CONFLICT: 409,
    HTTP_STATUS_INTERNAL_SERVER_ERROR: 500,
    HTTP_STATUS_NOT_IMPLEMENTED: 501,
    HTTP_STATUS_SERVICE_UNAVAILABLE: 505, 
    HTTP_CLIENT_CALLBACK: '/',
    HTTP_HEADER_ORIGIN: 'Origin',

    ROLE_SUPER_ADMIN: 'superAdmin',
    ROLE_ADMIN: 'admin',
    ROLE_STAFF: 'staff',
    ROLE_MEMBER: 'member',
 
    //Photo types
    PHOTO_TYPES_GALLERY:"Gallery",
    PHOTO_TYPES_FOOD:"Event",
    PHOTO_TYPES_OTHER:"Other",

    //Communication Types
    CONTACT_TYPE_EMAIL: "email",
    CONTACT_TYPE_PHONE: "phone",

    //Queue
    PHOTO_ARRIVAL_QUEUE: "PHOTO_ARRIVAL_QUEUE"
}
